import Head from "next/head";
import dynamic from "next/dynamic";

const Whiteboard = dynamic(() => import("../core/Whiteboard"), { ssr: false });

export default function Home() {
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Whiteboard />
		</>
	);
}
